### ISSUE TITLE
Suggestion: use smaller profile picture

### ISSUE THREAD

**Issue by ivanalejandro0** [viveknathani/vivekn.dev#1]
Hey there, I reached your website https://vivekn.dev/ from your math app linked on hacker news and I noticed your profile picture was a bit slow to load.

Looking at https://github.com/viveknathani/vivekn.dev/blob/4003a8184b013ebb31e09f22db0c4d93f1589651/src/static/index.html#L26 I see that you're loading a 1.5mb picture.

On desktop and fast networks it may not be noticeable sometimes, but for mobile and specially on slow and/or reduced data plans it may be problematic for visitors.

Also, depending on the traffic and provider, it may get cheaper to serve smaller images since you'll use less bandwidth.

I think that for the circular avatar use case you can get away with a much smaller image (around 100k or less), and maybe if you want people to have access to the original picture, the avatar could be a link o the original picture.

Cheers.

**Comment by viveknathani** [comment]
hi @ivanalejandro0!

thanks for pointing this out in a detailed manner, i appreciate your concern. 🙌

i have [pushed a fix](https://github.com/viveknathani/vivekn.dev/commit/43d7adeb889742bca4c9211abec577a914c3ea2f) for this. the size of the image now is ~188KB. 

marking this issue as closed now.

cheers!
